version: "3.0"
services:
  hdpselenium:
    image: selenium/standalone-chrome
    container_name: hdpselenium
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
    networks:
      - hdpnetwork
  hdpredis:
    image: redis
    container_name: hdpredis
    ports:
      - "6379:6379"
    networks:
      - hdpnetwork
  hdpjava:
    build:
      context: ./hdpjava
    image: hdpjava
    container_name: hdpjava
    ports:
      - "8080:8080"
    networks:
      - hdpnetwork
networks:
  hdpnetwork:
    driver:  bridge